### ISSUE TITLE
is there any way to make the tab bar autohide like how edge does it?

### ISSUE THREAD

**Issue by Revnae** [tovifun/VivalArc#21]
like i kinda want it to be like this 
https://arc.tovi.fun/assets/screenshot=2.jpg

but when i hover over that i shows the full tab

**Comment by everpromos** [comment]
Yes, agree

**Comment by tovifun** [comment]
I’m working on it. It’s a bit difficult for me.😂

**Comment by everpromos** [comment]
👍👍👍

**Comment by Zettry** [comment]
@tovifun I tried to achieve this effect, but there are still some issues. 

![vivalarc-tabbar](https://github.com/user-attachments/assets/4a32dab4-1595-45d0-ae82-dbb1651eca4d)

The changes are as follows:

1. Comment out the tabbar margin setting in `vivalarc.css`;

![image](https://github.com/user-attachments/assets/b16c3f37-12c7-4a2e-b765-bef6bd92aff0)

2. Create a new file called `vivalarc-tabbar.css` in the config folder.

```css
:root{
    --tabbar-size: 32px;
}

/* tabbar workspace */
.inner > .tabbar-wrapper:not(:hover) .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu{
    width: var(--tabbar-size)!important;
}
.inner > .tabbar-wrapper:not(:hover) .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-title,
.inner > .tabbar-wrapper:not(:hover) .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-toolbar-menu-indicator{
    display: none;
}

/* tabbar container */
.inner > .tabbar-wrapper:not(:hover) #tabs-tabbar-container,
.inner > .tabbar-wrapper:not(:hover) #tabs-tabbar-container .resize{
    width: var(--tabbar-size)!important;
}

/* tab stacking - accordion toggle arrow position */
#tabs-container.left .tab-position.accordion-toggle-arrow{
    --PositionX: 4px!important;
}

.inner > .tabbar-wrapper{
    position: relative;
    width: var(--tabbar-size);
}

.inner > .tabbar-wrapper > .tabbar-wrapper{
    position: absolute;
    background-image: url("chrome://vivaldi-data/thumbnail/WVKXPHMBICN2BPZCJFRT6B4RYYRCN6JS.png");
    background-size: cover;
    overflow: hidden;
    /* transition is not working */
    transition: width 0.3s ease-in-out;
    z-index: 1;
}
```

The issues that remain:

1. The background-image of the tabbar is now using a thumbnail. Different users might need to change it manually;
2. The transition animation when the tabbar expands is not working;
3. There is a problem with showing the menu when right-clicking on the tabbar.

I hope you can continue to improve it. Thank you!

**Comment by tovifun** [comment]
I gave it a try, and I think the result is already great!!!
I’ll try to continue refining it based on your style.

**Comment by Zettry** [comment]
@tovifun The transition animation is working now!!

![vivalarc-tabbar](https://github.com/user-attachments/assets/95db7565-b911-4438-bf7c-53c51b3e0053)

```css
:root{
    --tabbar-size: 32px;
}

/* tabbar workspace */
.inner > .tabbar-wrapper:not(:hover) .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu{
    width: var(--tabbar-size)!important;
    transition: unset;
}

.inner > .tabbar-wrapper:not(:hover) .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-title,
.inner > .tabbar-wrapper:not(:hover) .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-toolbar-menu-indicator{
    display: none;
}

.inner .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-icon{
    position: absolute;
    left: 5px;
}

.inner .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-title{
    position: absolute;
    left: var(--tabbar-size);
}

.inner .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-toolbar-menu-indicator{
    position: absolute;
    right: 5px;
}

/* tabbar container */
.inner > .tabbar-wrapper:not(:hover) #tabs-tabbar-container,
.inner > .tabbar-wrapper:not(:hover) #tabs-tabbar-container .resize{
    width: var(--tabbar-size)!important;
    transition: unset;
}

/* tab stacking - accordion toggle arrow position */
#tabs-container.left .tab-position.accordion-toggle-arrow{
    --PositionX: 4px!important;
}

.inner > .tabbar-wrapper{
    position: relative;
    width: var(--tabbar-size);
}

.inner > .tabbar-wrapper > .tabbar-wrapper{
    position: absolute;
    background-image: url("chrome://vivaldi-data/thumbnail/WVKXPHMBICN2BPZCJFRT6B4RYYRCN6JS.png");
    background-size: cover;
    overflow: hidden;
    z-index: 1;
}

.inner #tabs-tabbar-container,
.inner .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu {
    transition: width 0.5s;
}
```

**Comment by tovifun** [comment]
@Zettry 
a new version was released with a variant (available for use at ../vivalarc-autotab).

**_This version adds the above CSS styles to the default style👍_**, with a few small adjustments:

1. Vivaldi 7.0 introduced a density setting, where the tab gaps differ between default and compact density. The tab width now accounts for this adjustment.
2. The hover effect requires a local background image, which is a bit complex to set up, so I used a background color as a substitute. I think the effect is good; the interface remains clean by default, with the color appearing only on hover.
3. The animation duration has been adjusted from 0.5 seconds to 0.1 seconds.

![tabbar_hover_color](https://github.com/user-attachments/assets/643f5b96-71d7-4c53-9f11-b9bf4f57f734)


**_here are still a few unresolved issues:_**
1. When there are too many tabs and a scrollbar appears, further optimization is needed.
2. This style performs well in Vivaldi 7.0, but testing is still needed for previous versions of vivaldi.

https://github.com/user-attachments/assets/b72ab393-5730-4899-b815-5e076f1ef55e

**Comment by Zettry** [comment]
@tovifun hi, this is a completely hidden version.

```css
:root{
    --tabbar-size: 0px;
}

/* tabbar transparent */
.inner > .tabbar-wrapper:not(:hover) .tabbar-wrapper div {
    opacity: 0;
}

/* tabbar workspace */
.inner > .tabbar-wrapper:not(:hover) .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu{
    width: calc(var(--tabbar-size) + var(--densityGap))!important;
    transition: unset;
}

.inner > .tabbar-wrapper:not(:hover) .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-title,
.inner > .tabbar-wrapper:not(:hover) .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-toolbar-menu-indicator{
    display: none;
}

.inner .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-icon{
    position: absolute;
    left: var(--densityGap);
}

.inner .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-title{
    position: absolute;
    left: calc(32px + var(--densityGap)) !important;
}

.inner .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu .button-toolbar-menu-indicator{
    position: absolute;
    right: var(--densityGap);
}

/* tabbar container */
.inner > .tabbar-wrapper:not(:hover) #tabs-tabbar-container,
.inner > .tabbar-wrapper:not(:hover) #tabs-tabbar-container .resize{
    width: calc(var(--tabbar-size) + var(--densityGap)) !important;
    transition: unset;
}


.inner > .tabbar-wrapper{
    position: relative;
    width: calc(var(--tabbar-size) + var(--densityGap));
}

.inner > .tabbar-wrapper > .tabbar-wrapper{
    position: absolute;
    overflow: hidden;
    z-index: 1;
}

.inner > .tabbar-wrapper > .tabbar-wrapper:hover{
    position: absolute;
    background:var(--colorImageLeftBg, var(--colorBgLight)) ;
}

.inner #tabs-tabbar-container,
.inner .button-toolbar.workspace-popup.tabbar-workspace-button.button-menu {
    transition: width 0.1s;
}

/* hide tabbar scrollbar */
#browser #tabs-container.right ::-webkit-scrollbar,
#browser #tabs-container.left ::-webkit-scrollbar{
    display: none;
}

/* tab close button position */
.overflow.tab-strip .tab .tab-header{
    max-width: calc(var(--Width) + 12px)
}
```


https://github.com/user-attachments/assets/875e117d-ff8e-46d6-a265-c5cb925bd1fe
